check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
    each:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
        excludes: []
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes:
        - src/app/*.js
