sudo: false
language: node_js
node_js:
  - "6"
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: eu-west-1
  bucket: printing-engine-client.all3pd.com
  acl: public_read
  local_dir: dist
  on:
    repo: all3dp/printing-engine-client
    branch: master